channels:
- conda-forge
dependencies:
- python=3.9.6
- pip<=24.0
- pip:
  - mlflow==2.13.0
  - cloudpickle==3.0.0
  - numpy==1.26.4
  - packaging==24.0
  - pandas==2.2.1
  - psutil==5.9.8
  - pyyaml==6.0.1
  - scikit-learn==1.4.2
  - scipy==1.12.0
  - xgboost==2.0.3
name: mlflow-env
